### ISSUE TITLE
Adding custom properties to "profile"

### ISSUE THREAD

**Issue by 215699p** [Soluto/oidc-server-mock#103]
This project is great - it meets almost all of our needs, but I've been struggling with adding custom properties to the "profile" claim - is this possible out of the box or does it require a custom ProfileProvider?

**Comment by AleF83** [comment]
Hey,
Thanks,
You can add user with custom claims... 
https://github.com/Soluto/oidc-server-mock#user-management
Does it what you need?

**Comment by 215699p** [comment]
Hi, sorry for the delay in responding.

We weren't able to get this to work the way we wanted & we're not sure why.

Either way, we've dropped the idea of using a mock to solve the problem that we had.

Thanks for a nifty project - I'll definitely come back in the future if we have a need for it!
