### ISSUE TITLE
auto login

### ISSUE THREAD

**Issue by karthik233** [Soluto/oidc-server-mock#105]
I am from testing background, and needed some information
I have setup oidc mock for automated test execution as we cant use SSO login in docker/container test env.

My question is, wanted to know if we can automatically login when user clicks "login" button. Can this support multiple user? eg. each test env having different user for login. 

**We are not using implicit flow**
"AllowedScopes": [
      "openid",
      "profile",
      "email",
    ],

**Comment by AleF83** [comment]
What do you mean "login"? what flow do you use?

**Comment by karthik233** [comment]
so we have application, where login is needed. In typical scenario when login is clicked, SSO login happens. As we are planning to execute tests in test environment we are planning to use mock for login. 

we are used implicit flow

wanted to know if we can mimic the behaviour of SSO

**Comment by AleF83** [comment]
You can implement the flow just as in [e2e tests](https://github.com/Soluto/oidc-server-mock/blob/master/e2e/helpers/authorization-endpoint.ts). You should use [playwright](https://playwright.dev/) or other similar library for login page.
