### ISSUE TITLE
Health check doesn't work because curl isn't available

### ISSUE THREAD

**Issue by sorokya** [Soluto/oidc-server-mock#107]
Noticed that health was always being reported as unhealthy. When I shelled into the container to try running the health command it says curl isn't installed.

```
root@09084622fbd4:/OpenIdConnectServerMock# curl -f http://localhost/health
bash: curl: command not found
```

**Comment by AleF83** [comment]
Oh.
I'll check.
Maybe something changed in .NET base image... 
Thanks for noticing me

**Comment by AleF83** [comment]
Fixed.
Just published [new](https://github.com/Soluto/oidc-server-mock/pkgs/container/oidc-server-mock/24897352?tag=0.5.2) image version
