### ISSUE TITLE
IdentityServer4 is no longer maintained

### ISSUE THREAD

**Issue by pdf** [Soluto/oidc-server-mock#111]
The upstream developers have moved their development to a new org and will not support the old project going forward. Unfortunately the [new repo](https://github.com/DuendeSoftware/IdentityServer) comes with a non-free license, though they do allow it to be used "free" for non-commercial purposes.

Are there any plans to migrate this server to use the maintained upstream? I have [a bug](https://github.com/IdentityServer/IdentityServer4/issues/5463) that's breaking some applications in my dev env, but I'm not certain that will ever get fixed in the current upstream repo, and I suspect it's not easily fixed here either?

**Comment by AleF83** [comment]
Hey,
Yeah. I want to migrate the project to use the new library.
But cannot commit to specific date when it will be done.
I think it will take a couple of months.

**Comment by pdf** [comment]
I've started the work in #112 but unfortunately don't have the C#/dotnet experience to land it.

**Comment by AleF83** [comment]
Great! I'll try to find some time at weekend to continue!
Thanks for contributing!

**Comment by AleF83** [comment]
@pdf 
I managed to upgrade the project to use the new version of IdentityServer.
I created new [PR](https://github.com/Soluto/oidc-server-mock/pull/115) inspired by yours. There are some breaking changes that the new version introduces.

I can merge my PR or if you want to update yours (it's not up-to-date since I added some other features) I can add commit with required changes to your branch

**Comment by pdf** [comment]
Great news. I'm not particularly precious about it, I just wanted to help out and I know that starting a change like this can be a hurdle.

I'll leave it up to you how you want to land it - maintainer modifications are enabled on my PR but if you already have all the changes staged I won't be offended if you just merge them elsewhere.

**Comment by AleF83** [comment]
Great! I'll merge my branch due to shortage in time. I've added you as co-author to the commit.

Thank you for contributing!

**Comment by Str3amR** [comment]
Unfortunately this change imply a license change that now prevent us from using this project. It's still too early to tell what we will do in this case, but have you considered using an alternate framework like [Openiddict ](https://github.com/openiddict/openiddict-core) which have a compatible license?

The solution for us will probably ends up being to write another mock project using Openiddict.

**Comment by AleF83** [comment]
Hey, AFAIK Duende license is free for testing. It should be enough. This project doest suppose to be deployed to production.
