### ISSUE TITLE
404 for route /diagnostics after login

### ISSUE THREAD

**Issue by github-canni** [Soluto/oidc-server-mock#130]
Hey guys,

I upped a testing container with the default clients-config.json & docker-compose.yml as provided in the [README.md](https://github.com/Soluto/oidc-server-mock/blob/master/README.md)

Upon redirect after logging in, I get a 404 for /diagnostics page. User is successfully logged in. The log does not show an error.

Any clues?

Environement
I tried locally with default config (http) and I also tired running a reverse proxy nginx (https) + already fiddled with some proxy headers just in case. I do not use the SSL config from the HTTPS section in Readme but it seems unrelated to that.

```
# Mock OIDC
location / {
	proxy_pass http://127.0.0.1:4011/;
	proxy_buffer_size 16k;
	proxy_buffers 8 16k;
	
	proxy_set_header Origin https://{real-hostname};
	proxy_hide_header Access-Control-Allow-Origin;
	add_header Access-Control-Allow-Origin $http_origin;
		
	proxy_cache_bypass                    $http_upgrade;
	proxy_set_header Upgrade         $http_upgrade;
	proxy_set_header Connection     "upgrade";
        proxy_set_header Host                 $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto    $scheme;
        proxy_set_header X-Forwarded-Host     $host;
        proxy_set_header X-Forwarded-Port     $server_port;
        proxy_set_header Accept-Encoding      "";
        sub_filter_types *;
        sub_filter_once  off;
        proxy_read_timeout 3m;
        proxy_send_timeout 3m;			
}
```

**Comment by AleF83** [comment]
Hi @github-canni, 
I'm not familiar with the diagnostics page. Can you please elaborate more about it. Is it a part of IdentityServer? What should it contain?
