### ISSUE TITLE
Need Help!, Not able to override SID

### ISSUE THREAD

**Issue by kishorevarma** [Soluto/oidc-server-mock#137]
Hi there,

I have been to the previous issues, we have a similar issue in past, I tried all the solutions mentioned in the comments from that issue, but couldn't get the sid claim override. all other custom claims are coming in the id token. Please help me what I am doing wrong here. Thanks

My docker-compose config.

`oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - "4011:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      OVERRIDE_STANDARD_IDENTITY_RESOURCES: true
      IDENTITY_RESOURCES_INLINE: |
        [
          {
            "Name": "profile",
            "ClaimTypes": ["name", "email", "ShopperId", "ScvId", "sid"]
          },
          {
            "Name": "openid",
            "ClaimTypes": ["sub", "sid"]
          }
        ]
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1assafsdf",
            "Username":"User1",
            "Password":"pwd",
            "Claims": [
              {
                "Type": "name",
                "Value": "Sam Tailor",
                "ValueType": "string"
              },
              {
                "Type": "sid",
                "Value": "1232425252452",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "sam.tailor@gmail.com",
                "ValueType": "string"
              },
              {
                "Type": "ScvId",
                "Value": "123456780",
                "ValueType": "string"
              },
              {
                "Type": "ShopperId",
                "Value": "123456780",
                "ValueType": "string"
              }
            ]
          }
        ]
      CLIENTS_CONFIGURATION_PATH: /data/clients-config.json
      ASPNET_SERVICES_OPTIONS_INLINE: |
        { 
          "ForwardedHeadersOptions": { 
            "ForwardedHeaders" : "All"
          }
          "BasePath": "/protocol/openid-connect"
        }
    volumes:
      - ./MockServices/OIDC:/data
`
and my client config
`[
  {
    "ClientId": "trader",
    "ClientSecrets": ["client-credentials-mock-client-secret"],
    "Description": "Client for client credentials flow",
    "AllowedGrantTypes": ["authorization_code"],
    "RedirectUris": ["http://localhost:55520/api/v1.0/bff/login-callback"],
    "AllowedScopes": ["openid", "profile"],
    "ClientClaimsPrefix": "",
    "IdentityTokenLifetime": 3600,
    "AccessTokenLifetime": 3600,
    "RequirePkce": false,
    "AlwaysIncludeUserClaimsInIdToken": true
  }
]
`

**Comment by AleF83** [comment]
Hi,
Unfortunately, I think you cannot override this claim. [Here](https://github.com/DuendeSoftware/IdentityServer/blob/73dd86a7d7c58c34934c9e6af5d7e5730758fef5/src/IdentityServer/Services/Default/DefaultTokenService.cs#L172) we can see that custom claims are set before SID claim:

```cs
  var claims = new List<Claim>();
  claims.AddRange(await ClaimsProvider.GetAccessTokenClaimsAsync(
      request.Subject,
      request.ValidatedResources,
      request.ValidatedRequest));

  if (request.ValidatedRequest.SessionId.IsPresent())
  {
      claims.Add(new Claim(JwtClaimTypes.SessionId, request.ValidatedRequest.SessionId));
  }
```

**Comment by kishorevarma** [comment]
Thank you,
