### ISSUE TITLE
BasePath configuration is not working properly

### ISSUE THREAD

**Issue by ValentinLorand** [Soluto/oidc-server-mock#141]
Hello, I'm just tring to deploy this oidc-mock-server behind an apache2 reverse proxy. But I have some problems regarding the BasePath of the application.

I configured this json like your example : 
```
$ cat default_config/services-options.json 
{
	"BasePath": "/oidc-provider",    
	"ForwardedHeadersOptions": {
        	"ForwardedHeaders" : "All"
    	}
}
```

But It's not working the server tries to retrieve the resources from root path : 
![image](https://github.com/Soluto/oidc-server-mock/assets/47445051/2201250d-21e6-4e7f-a9cf-1d30df6a0b33)

Has anyone managed to configure the basepath ?

**Comment by ClementLagorce** [comment]
Hello, I tried to configure this variable aswell a few weeks ago and I was not able to make it work neither. I hope someone could bring more information about this issue !

**Comment by AleF83** [comment]
Hi,
Sorry for delay,
You can see the usage [here](https://github.com/Soluto/oidc-server-mock/blob/1b8405635311d8aeba8e77165f40d75b91f20eba/e2e/docker-compose.yml#L32) in E2E tests.

**Comment by ValentinLorand** [comment]
Hi, 
I just try again to configure the BasePath, as your example, with the `ASPNET_SERVICES_OPTIONS_INLINE` variable in the docker-compose. It doesn't work. In the logs, there is no trace of any base path. Are you able to configure this on your side ?

**Comment by AleF83** [comment]
It should work.
In tests, the [request to the token endpoint](https://github.com/Soluto/oidc-server-mock/blob/e1211c16a5eda7a5f3c9f76644c86b3c8b1c3b75/e2e/tests/base-path.spec.ts#L36) is done with [the base path](https://github.com/Soluto/oidc-server-mock/blob/e1211c16a5eda7a5f3c9f76644c86b3c8b1c3b75/e2e/.env#L9).
Also before that, there is [an assertion](https://github.com/Soluto/oidc-server-mock/blob/e1211c16a5eda7a5f3c9f76644c86b3c8b1c3b75/e2e/tests/base-path.spec.ts#L23) of discovery page that token point has base path.

**Comment by AleF83** [comment]
Closing due inactivity.
