### ISSUE TITLE
Getting ID Token for an integration test without the redirect dance

### ISSUE THREAD

**Issue by YarekTyshchenko** [Soluto/oidc-server-mock#15]
Is there anyway to get the ID token from resource owner grant, without having to go through the whole redirect business? I need to test an OIDC client that requires a correctly signed JWT token. Alternatively, is there a way to get (or set) the private keys used by the identity server?

**Comment by AleF83** [comment]
`oidc-server-mock` is base on [IdentityServer4](http://docs.identityserver.io/en/latest/index.html) library. It just allows to define configurations easily.
I don't think there is option in IdentityServer to perform such "silent" login in implicit flow.

Regarding the second question, can you elaborate more on the keys you've mentioned?

**Comment by AleF83** [comment]
I found [this](http://docs.identityserver.io/en/latest/topics/crypto.html#token-signing-and-validation) in IdentityServer documentation: 
"...
Loading of signing key and the corresponding validation part is done by implementations of ISigningCredentialStore and IValidationKeysStore. If you want to customize the loading of the keys, you can implement those interfaces and register them with DI.
..."

[Here](https://github.com/IdentityServer/IdentityServer4/blob/2d10ecee9b600a95a2bbe0ca9f2ab5a5b18a199c/src/IdentityServer4/host/Startup.cs#L71) is code that can help.

I'm to 100% sure but I think it's possible to inject keys via configuration.

If you can collaborate on the project it will be great. :-)
If not I can try to implement this functionality at the beginning of November.

**Comment by YarekTyshchenko** [comment]
That sounds good. Another option might be adding a custom endpoint (http://docs.identityserver.io/en/latest/topics/add_apis.html) that returns a signed token. It will make the test code significantly simpler.

I will take a lot next time I'm working on this (hopefully within a few weeks).

**Comment by xadvfh** [comment]
Also interested in this.  was there any progress or did someone figure out how to do this?
