### ISSUE TITLE
Restart server after configuration change

### ISSUE THREAD

**Issue by cburmeister** [Soluto/oidc-server-mock#17]
I'd like to use this in a scenario where we're required to generate our client/user configurations in another container. Is there a simple way to restart the server (maybe using `dotnet watch`?) when configuration files change?

**Comment by AleF83** [comment]
Hey.
Sorry for delay.
The client/user changing is not supported. The server defines clients using `AddInMemoryClients` method called on startup.
As mentioned [here](http://docs.identityserver.io/en/3.1.0/topics/clients.html) to support configuration changes it should be implemented using `IClientStore`.

You are welcome to contribute :-)
