### ISSUE TITLE
Wrong image published for 0.2.2

### ISSUE THREAD

**Issue by nigredo-tori** [Soluto/oidc-server-mock#23]
After upgrading from 0.2.1 to 0.2.2, I get the following when starting the container:

```
yarn run v1.22.4
$ mocha --require ts-node/register ./**/*.spec.ts --exit


  1) "before all" hook: waiting for oidc server & airbag in "{root}"

  0 passing (10s)
  1 failing

  1) "before all" hook: waiting for oidc server & airbag in "{root}":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It looks like the test image from /e2e got published instead of the one from /src, as can be seen from the layers [here](https://registry.hub.docker.com/layers/soluto/oidc-server-mock/0.2.2/images/sha256-a010e3e3c189f143f05e127f6814baab21b683aae6713b6d5688a5900bd62b7e?context=explore).

**Comment by AleF83** [comment]
Hey,
You're right. I shouldn't push images late at night :-)
Just pushed the right one.
