### ISSUE TITLE
SameSite cookie management

### ISSUE THREAD

**Issue by cgrass** [Soluto/oidc-server-mock#25]
Has anyone looked at supporting the new stricter samesite cookie standard? Chrome has [started enforcing the behavior](https://www.chromium.org/updates/same-site), so I see following exception after `/login`:
`A cookie associated with a resource at http://localhost/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.`

After reviewing https://www.thinktecture.com/en/identity/samesite/prepare-your-identityserver/ I was able to modify the server to return `SameSite=Lax` without much effort, but it's a simplistic approach. I assume a better implementation would be to allow the policy to be configurable.

**Comment by AleF83** [comment]
Hey @cgrass 

I think that cookie configuration can be added as described [here](https://identityserver4.readthedocs.io/en/latest/topics/signin.html#overriding-cookie-handler-configuration)

If I understand right the following configuration should be added to the server: 

```csharp
services.AddAuthentication()
                .AddCookie(options => {
                    options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;
                    options.Cookie.SecurePolicy = Microsoft.AspNetCore.Http.CookieSecurePolicy.Always;
                });
```

So the server should support cookie configuration file.
Does it make sense to you?

If yes you're welcome to contribute :-)

**Comment by cgrass** [comment]
> Hey @cgrass
> 
> I think that cookie configuration can be added as described [here](https://identityserver4.readthedocs.io/en/latest/topics/signin.html#overriding-cookie-handler-configuration)
> 
> If I understand right the following configuration should be added to the server:
> 
> ```cs
> services.AddAuthentication()
>                 .AddCookie(options => {
>                     options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;
>                     options.Cookie.SecurePolicy = Microsoft.AspNetCore.Http.CookieSecurePolicy.Always;
>                 });
> ```
> 
> So the server should support cookie configuration file.
> Does it make sense to you?
> 
> If yes you're welcome to contribute :-)

yup, something very similar works locally. if we're not worried about making that configurable, then i'll create a PR this week. Thanks for the reply.

**Comment by AleF83** [comment]
I mean to add function to `Config.cs` that will parse json from file/env (like all other configurations) and then to merge the parsed object into the options argument of the `AddCookie` function.

**Comment by tinohager** [comment]
When we are use `https` we only need the `Secure` attribute on `set-cookie`

```
version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - oidc-server-mock
    restart: always
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://oidc-server-mock:80'

  oidc-server-mock:
    container_name: oidc-server-mock
    image: soluto/oidc-server-mock
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          }
        }
      API_SCOPES_INLINE: |
        [
          "some-app-scope-1",
          "some-app-scope-2"
        ]
      API_RESOURCES_INLINE: |
        [
          {
            "Name": "some-app",
            "Scopes": ["some-app-scope-1", "some-app-scope-2"]
          }
        ]
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"admin",
            "Password":"password1234"
          }
        ]
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
    volumes:
      - .:/tmp/config:ro
```

**Comment by tinohager** [comment]
my changes https://github.com/Soluto/oidc-server-mock/pull/40/files

**Comment by nigredo-tori** [comment]
What's the status on this? @tinohager's `steveltn/https-portal` solution doesn't seem to work when using unorthodox ports.

**Comment by AleF83** [comment]
@nigredo-tori 
What scenario do you have?

There is development certificate in the repo. **I've added it to keychain on my machine.**
I ran `docker-compose up` from `e2e` folder and then opened `https://localhost:8443/grants`. I logged in successfully.

When I open `http://localhost:8080/grants` I encounter the issue and cannot pass login page.

**Comment by nigredo-tori** [comment]
@AleF83, I apologize, I wasn't aware of the new [https settings](https://github.com/Soluto/oidc-server-mock#https). With those (and oidc-server-mock 0.2.4), authentication does indeed work OK over HTTPS, even with remapped ports. Thank you!

**Comment by AleF83** [comment]
@nigredo-tori  NP.

@cgrass Does running the server with trusted certificate  and configuration as shown in test  solves the issue for your case?

https://github.com/Soluto/oidc-server-mock/blob/96a8a430aa1ef419ad775a419dc1d826cd08c50f/e2e/docker-compose.yml#L18

**Comment by AleF83** [comment]
So summarizing the issue.
There are two ways to solve it.
1. Leave cookie SameSite mode to default (`None`) and make calls the server via HTTPS protocol.
2. Change cookie SameSite mode to `Lax` and use HTTP protocol. It can be done by setting the following in `SERVER_OPTIONS_PATH` env var
```json
{
  "Authentication": {
    "CookieSameSiteMode": "Lax",
    "CheckSessionCookieSameSiteMode": "Lax"
  }
}
```
