### ISSUE TITLE
Difficulty authenticating for introspection endpoint

### ISSUE THREAD

**Issue by ljdursi** [Soluto/oidc-server-mock#33]
I'm having a tough time authenticating an API for introspection of the token.  For the provided configuration in the docker-compose file, what is the right way to provide a secret for the API?  Do I add an ApiSecrets array to the `some-app` API resource?

**Comment by AleF83** [comment]
Hey @ljdursi .
I've fixed the bug related to api resources secret  serialization bug and released v0.2.3.
You can see [this test](https://github.com/Soluto/oidc-server-mock/blob/master/e2e/tests/introspection-endpoint.spec.ts) for example of usage.

Thank you for the issue.

**Comment by ljdursi** [comment]
Thanks for the very quick response and update!  It works for me now.  Thanks so much!
