### ISSUE TITLE
Add support for wildcard redirect urls

### ISSUE THREAD

**Issue by Yshayy** [Soluto/oidc-server-mock#43]
In some cases, the localhost redirect is not good enough if we use a remote environment (like codespaces or gitpod.io) that can use generated urls. (the server can run on something like some-dev-space-zq1.cloudsomething.io).

It should be possible to implement by using AddRedirectUriValidator.
https://identityserver4.readthedocs.io/en/release/topics/startup.html

Adding support for "*" or "*.devspace.io" can solve this issue

**Comment by AleF83** [comment]
Thank you for contributing.
I'll publish new version in few days.
