### ISSUE TITLE
Confusion between subject id and username => "User is not active"

### ISSUE THREAD

**Issue by plexibert** [Soluto/oidc-server-mock#56]
It seems there's a mixup in https://github.com/Soluto/oidc-server-mock/blob/master/src/Services/ProfileService.cs#L34 between userName and SubjectId. The following check ` u.Username == userName)` appears to compare the requested subject id against all userNames in the `IEnumerable` -- this fails and the user is marked as inactive.

The fix is trivial, but maybe the entire task should fail if the user cannot be found?

**Comment by AleF83** [comment]
Hey @plexibert 
Thank you for bringing this to my attention.
I've fixed the bug (#57 ) and replaced the Docker image with the new one.

Regarding to the task failure. I'm not sure.
In the IdentityServer4 project there is sample of the ProfileService implementation. 
https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Test/TestUserProfileService.cs#L70

I've implemented the same login in case of non-existing user.
WDYT?

**Comment by plexibert** [comment]
Thanks for the quick fix!

I don't really know the code, I was simply thinking about _when would a user be authenticated but not in the `IEnumerable`_? At first glance, this looks like an inconsistency (between which users exist for authentication and which users exist for isActive). Such an inconsistency could be promimently reported as an exception (though I don't know how IdentityServer deals with exceptions in this context).

But it's not clear to me if there's a valid scenario where a user is removed between authentication and checking for IsActive. If there is one, then of course the response should be _task complete, result is false_. In other words, I haven't yet looked at how the authentication works and how it accesses the list of existing users.

Btw, did you notice the IdentityServer4 repo is in maintenance mode now? They're apparently moving new development to another repo.

**Comment by AleF83** [comment]
IMO both scenarios are legit. Maybe it worth to add configuration flag for throwing/returning not active states.
