### ISSUE TITLE
Using https with termination in haproxy/nginx

### ISSUE THREAD

**Issue by 808brinks** [Soluto/oidc-server-mock#66]
I'm trying to use the docker in my docker environment where SSL is terminated in haproxy. How can I convince oidc-server-mock to give me https url's when calling `.well-known/openid-configuration` urls?

I found IssuerUrl in  https://identityserver4.readthedocs.io/en/latest/reference/options.html but i don't seem to be able to pass this to the docker.

**Comment by AleF83** [comment]
Hey,
You can set `issuerUrl` using `SERVER_OPTIONS_INLINE/PATH` environment variable.
See example here:  https://github.com/Soluto/oidc-server-mock/blob/f265c212303e66de6e3a57c26b37d58be2552108/e2e/docker-compose.yml#L12

**Comment by 808brinks** [comment]
I did try adding it there but it didn't seem to affect the URLs in .well-known/openid-configuration.

**Comment by AleF83** [comment]
I've run the image with 443 port and got all urls with https:

```yaml
 ASPNETCORE_URLS: https://+:443
```

Discovery page:

```json
/ 20210203104450
// https://localhost:8443/.well-known/openid-configuration

{
  "issuer": "https://localhost:8443",
  "jwks_uri": "https://localhost:8443/.well-known/openid-configuration/jwks",
  "authorization_endpoint": "https://localhost:8443/connect/authorize",
  "token_endpoint": "https://localhost:8443/connect/token",
  "userinfo_endpoint": "https://localhost:8443/connect/userinfo",
  "end_session_endpoint": "https://localhost:8443/connect/endsession",
  "check_session_iframe": "https://localhost:8443/connect/checksession",
  "revocation_endpoint": "https://localhost:8443/connect/revocation",
  "introspection_endpoint": "https://localhost:8443/connect/introspect",
  "device_authorization_endpoint": "https://localhost:8443/connect/deviceauthorization",
```

**Comment by 808brinks** [comment]
What is your issuerUrl in this example?

**Comment by AleF83** [comment]
Didn't set it at all. By default it's the server url.

**Comment by 808brinks** [comment]
Ah yes. The point is in my setup haproxy terminates ssl and nginx is setup in a reverse proxy. So I don't need the mock to listen on the SSL port(433) I just need it to reply with urls like it is.

So in the well-known I would want ` "issuer": "https://openid-mock.docker" ` etc. 
Even though the mock is actually running no port 80 with container name `openid-mock`.

**Comment by AleF83** [comment]
> Hey,
> You can set `issuerUrl` using `SERVER_OPTIONS_INLINE/PATH` environment variable.
> See example here:
> 
> https://github.com/Soluto/oidc-server-mock/blob/f265c212303e66de6e3a57c26b37d58be2552108/e2e/docker-compose.yml#L12

So this is the answer
