### ISSUE TITLE
cookies option in the wrong place?

### ISSUE THREAD

**Issue by xadvfh** [Soluto/oidc-server-mock#77]
hello, in the readme you have:

```
Change cookies SameSite mode from default None to Lax. To do so just add the following to SERVER_OPTIONS_INLINE/PATH env var:
```

looking at the  code, the authentication key is read from `ASPNET_SERVICES_OPTIONS_PATH`.  Is this a typo or am I not understanding how to do this?

**Comment by xadvfh** [comment]
@AleF83 any idea on this?  I'm bringing this up because for some reason when i run my tests through chrome headless `oidc-server-mock` is not redirecting back to my app.  When I run non-headless it works fine.  I was wondering maybe the same-site cookie settings were not being applied correctly or maybe some other issue.

**Comment by AleF83** [comment]
Hey, you're right. There was mistake in docs. I'll try to check the issue about headless chrome. But I'm a little bit busy these days with other project. Sorry :-}
