### ISSUE TITLE
Timeframe for implementing PUT and DELETE requests?

### ISSUE THREAD

**Issue by chris468** [Soluto/oidc-server-mock#78]
Great project - I had started to build the something similar when I found this.

Do you have a timeframe for implementing the PUT and DELETE requests? If I need them before you get to them would you accept a pull request?

Thanks
-Chris

**Comment by AleF83** [comment]
Hey,
I don't have timeframes.. I add features only when I need them for my other projects.
But I definitely will accept PRs!
It will be greate!

**Comment by chris468** [comment]
Sounds good, thanks!
