### ISSUE TITLE
 Setting of root url 

### ISSUE THREAD

**Issue by Ochir** [Soluto/oidc-server-mock#82]
Sorry, I decided to re open another issue instead of #81 . 

in other words, I need to find a way to run oidc-server-mock at some URL with subpath like <server_url>/app1.

There is no info about changing this URL for docker image.

I googled and found out that inside code a PathBase should be set but I didn't find it in the code.

**Comment by AleF83** [comment]
Hey,
I think #87 solves your problem, is it?

**Comment by Ochir** [comment]
Yes, it looks like this is what I need. thank you!
