### ISSUE TITLE
Image on docker hub running behind

### ISSUE THREAD

**Issue by bertbaron** [Soluto/oidc-server-mock#88]
The latest tag of this useful mock server on docker hub for soluto/oidc-server-mock is still 0.3.2. Is there any chance that this will be updated soon?

Regard, Bert

**Comment by AleF83** [comment]
Hey, I migrated to `github` packages
Please use the following:
```bash
docker pull ghcr.io/soluto/oidc-server-mock:0.4.2
```

I'll update the docks to make it clear

**Comment by bertbaron** [comment]
Thanks for the update
