### ISSUE TITLE
Healthcheck timeout is too short in 0.4.3 leading to unhealthy status

### ISSUE THREAD

**Issue by mjustin** [Soluto/oidc-server-mock#96]
A number of healthcheck parameters were tuned in #94 to resolve #93.  However, (on my machine with its current load, at least), the new timeout of 100ms is too short, leading to the status coming back as "unhealthy".

It looks like this value should be increased.  The Docker default of 30s works fine on my machine, as does 1s (if decreasing it is desirable).  It seems to work all the way down to 130ms on my current machine, so it's currently _almost_ fast enough…

---

## `docker-compose.yml` workaround

I'm able to work around this issue by manually specifying the healthcheck timeout in my `docker-compose.yml` file:

```lang-yaml
version: '3'
services:
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - "4011:80"
    volumes:
      - .:/tmp/config:ro
    environment:
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
    healthcheck:
      timeout: 30s
```

**Comment by andreas-mausch** [comment]
Thanks for the workaround!
